site_name: "Маркозубова Анастасия Отчеты"
theme:
  name: 'material'
  palette:
    primary: 'black'
    accent: 'pink'
nav:

  - Лабораторная работа №1:
    - Задание 1: lab1/task_1.md
    - Задание 2: lab1/task_2.md
    - Задание 3: lab1/task_3.md
    - Задание 4: lab1/task_4.md
    - Задание 5: lab1/task_5.md
  - Лабораторная работа №2:
      - Отчёт: lab2/report.md
 
markdown_extensions:
  - codehilite
  - pymdownx.highlight
  - pymdownx.superfences


